(defun peak-index-in-mountain-array (arr)
  (labels ((helper (rr)
             (cond ((= 1 (length rr))
                    0)
                   ((> (first rr) (second rr))
                    0)
                   ((= 2 (length rr))
                    1)
                   (t (let ((mid (floor (/ (length rr) 2))))
                        (let ((ai (helper (subseq rr 0 mid)))
                              (bi (+ mid (helper (subseq rr mid)))))
                          (if (> (nth ai rr) (nth bi rr))
                              ai
                              bi)))))))
    (helper arr)))

(peak-index-in-mountain-array '(0 1 0))
(peak-index-in-mountain-array '(0 2 1 0))
(peak-index-in-mountain-array '(0 10 5 2))
