(ql:quickload "alexandria")

(defun is-valid (s)
  (labels ((helper (chars stack)
             ;;(format t "~a ~a~%" chars stack)
             (alexandria:if-let (first (car chars))
               (cond ((char= first #\a)
                      (push #\c stack)
                      (push #\b stack)
                      (helper (cdr chars) stack)
                      )
                     ((not (car stack)) nil)
                     ((char= first (car stack))
                      (pop stack)
                      (helper (cdr chars) stack))
                     (t nil))
               (= 0 (length stack)))))
    (helper (concatenate 'list s) '())))

(defun main ()
  (assert (is-valid "aabcbc"))
  (assert (is-valid "aabcbcabcabcababcc"))
  (assert (not (is-valid "abccba")))
  (assert (not (is-valid "aaabc")))
  )
