(defun has-special-substring (s k)
  (do* ((ss (concatenate 'list s) (cdr ss))
        (start nil)
        (end (nth k ss) (nth k ss)))
       (() nil)
    ;;(pprint ss)
    (if (every (lambda (n) (equal n (nth 0 ss))) (subseq ss 0 k))
        (cond ((and (not start) (not end))
               (return-from has-special-substring t))
              ((and (not start) (not (equal end (nth 0 ss))))
               (return-from has-special-substring t))
              ((and (not end) (not (equal start (nth 0 ss))))
               (return-from has-special-substring t))
              ((and (not (equal start (nth 0 ss)))
                    (not (equal end (nth 0 ss))))
               (return-from has-special-substring t)
               )))
    (setf start (nth 0 ss))
    (if (not end) (return-from has-special-substring nil))))

(defun main ())
