(defun kill-process (pid ppid kill)
  (let ((tempHash (make-hash-table))
        (result '())
        (stack (list kill)))
    (loop for ind from 0 to (length ppid)
       do (setf (gethash id tempHash)
                (if (eql nil (gethash id tempHash))
                    (nth )
                    (1+ (gethash id tempHash)))))))
