;; Area = 1/2 |(x1y2 + x2y3 + x3y1) - (x2y1 + x3y2 + x1y3)
(defun largest-triangle-area (points)
  (labels ((cal-area (p0 p1 p2)
             (let ((x0 (first p0))
                   (y0 (second p0))
                   (x1 (first p1))
                   (y1 (second p1))
                   (x2 (first p2))
                   (y2 (second p2)))
               (/ (abs (- (+ (* x0 y1)
                             (* x1 y2)
                             (* x2 y0))
                          (+ (* x1 y0)
                             (* x2 y1)
                             (* x0 y2))))
                  2.0))))
    (loop for i from 0 below (length points)
          maximize (loop for j from (1+ i) below (length points)
                         maximize (loop for m from (1+ i) below (length points)
                                        maximize (cal-area (nth i points)
                                                           (nth j points)
                                                           (nth m points)))))))

(largest-triangle-area '((0 0) (0 1) (1 0) (0 2) (2 0)))
(largest-triangle-area '((1 0) (0 0) (0 1)))
(largest-triangle-area '((4 6) (6 5) (3 1)))
