(defun isAnagram (s tt)
  (let ((ss (coerce s 'list))
        (ttt (reverse (coerce tt 'list))))
    ;(print ss)
    ;(print ttt)
    (return-from isAnagram (listpp ss ttt))))

(defun listpp (list1 list2)
  (cond ((equal list1 list2) (return-from listpp 'true))
        (t (return-from listpp 'false))))
