(defun find-max-consecutive-ones (nums)
  (let ((result 0)
        (tmp 0))
    (dolist (n nums (if (> tmp result) tmp result))
      (if (= 1 n)
          (incf tmp)
          (progn (if (> tmp result)
                     (setf result tmp))
                 (setf tmp 0))))))
