;; this function looks such ugly LOL

(defun find-unsorted-subarray (nums)
  (let ((newNums (sort (copy-seq nums) #'<)))
    (do ((point 0 (1+ point))
         (startInd -1)
         (endInd (length nums)))
        ((= (length nums) point)
         (cond ((and (= startInd -1)
                     (= endInd (length nums)))
                0)
               (t (- endInd startInd))))
      (cond ((and
              (/= (nth point nums)
                  (nth point newNums))
              (= startInd -1))
             (setf startInd point))
            ((and
              (/= (nth point nums)
                  (nth point newNums))
              (/= startInd -1)
              (setf endInd (length nums))))
            ((and
              (= (nth point nums)
                 (nth point newNums))
              (/= startInd -1))
             (setf endInd point)))
      )))

(defun main ()
  (let  ((test1 '(1 2 3))
         (test2 '(1))
         (test3 '(2 6 4 8 10 9 15))
         (test4 '(2 6 4 8 10 15 9))
         (test5 '())
         (test6 '(3 2 1)))
    (print (find-unsorted-subarray test1))
    (print (find-unsorted-subarray test2))
    (print (find-unsorted-subarray test3))
    (print (find-unsorted-subarray test4))
    (print (find-unsorted-subarray test5))
    (print (find-unsorted-subarray test6))
    ))
