(defun sumBinary (n)
  (do* ((num n (/ (- num (evenIf num)) 2))
        (sum 0 (+ (evenIf num) sum)))
       ((= num 1) (return-from sumBinary (if (oddp n)
                                             (+ sum 1)
                                             sum)))))
(defun evenIf (num)
  (if (evenp num) 
      (return-from evenIf 0)
      (return-from evenIf 1)))
