(defun is-subsequence (s j)
  (labels ((inner (s j)
             (cond ((= 0 (length s)) t)
                   ((= 0 (length j)) nil)
                   ((eq (car s) (car j))
                    (inner (cdr s) (cdr j)))
                   (t (inner s (cdr j))))))
    (inner (concatenate 'list s)
           (concatenate 'list j))))
